In [23]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
from sklearn.datasets import fetch_california_housing
housing  = fetch_california_housing()

In [5]:
df_x = pd.DataFrame(housing.data,columns = housing.feature_names)
df_y = pd.DataFrame(housing.target)

In [9]:
df_x.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

In [10]:
reg = linear_model.LinearRegression()

In [13]:
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size = 0.2,random_state = 4)

In [15]:
reg.fit(x_train,y_train)

LinearRegression()

In [17]:
reg.coef_

array([[ 4.36566858e-01,  9.37331719e-03, -1.09689383e-01,
         6.25836146e-01, -5.45292404e-06, -3.49194521e-03,
        -4.24368841e-01, -4.38492195e-01]])

In [31]:
a = reg.predict(x_train)

In [33]:
a[2]

array([1.74978106])

In [33]:
y_test

0
6939   1.752
8032   3.147
18877  0.900
4882   1.231
5409   3.509
...      ...
6634   2.618
18858  0.342
8910   3.750
9712   1.897
1118   1.152

[4128 rows x 1 columns]

In [35]:
a[3]

array([1.24712306])